language: node_js
node_js:
  - "6"
  - "6.4"
  - "5"
  - "5.1"
  - "4"
  - "4.3"
  - "4.2"
  - "node"
script: "npm run-script travis-test"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
